version: "3.8"

services:
# backend service
  node_backend: 
    container_name: prueba-tecnica-tyba

    image: prueba-tecnica-tyba:0.0.1
    
    build:
      context: .

    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE=myapp_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=postgres_db
    depends_on:
      - postgres_db

# database service
  postgres_db: 
    container_name: postgres_db

    image: "postgres:latest"

    ports: 
      - "3001:3001"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp_db
    volumes:
      - nps_data:/var/lib/postgres/database
  

# volumes
volumes:
  nps_data: {}

